### ISSUE TITLE
Input format for merging VCFs

### ISSUE THREAD

**Issue by mkirsche** [dbeyter/sv-merger#1]
Hi,

I have a set of VCF files containing SVs called from Sniffles that I am interested in merging using your software.  However, from the test data on this repo it looks like sv-merger doesn't accept the VCF format as input.  Is there a script to convert VCF files to a format which sv-merger accepts, or otherwise some documentation describing the input format?

Thanks!
Melanie

**Comment by dbeyter** [comment]
Hi Melanie, 

Thank you for your question. You're right, it does not accept the VCF format as input at the moment. I added documentation to the README for the input format that is accepted. 

As of now, SVs from all set of samples/individuals that can be merged together are expected to exist in a single input file. One pre-processing that is also needed is a pre-clustering on the SVs to provide a rough grouping of the SVs, such that two SVs that are guaranteed not to be merged together are given two different cluster ids. I also described this in the README. 

We provided more detail in the section "6. SV merging pre-processing" in the Supplementary Information of [our paper](https://www.nature.com/articles/s41588-021-00865-4)

Link for : [Supplementary Information](https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-021-00865-4/MediaObjects/41588_2021_865_MOESM1_ESM.pdf )

Please let me know if you have further questions or comments!

Thank you,
Doruk

**Comment by mkirsche** [comment]
Hi Doruk,

Thank you for the information - it is much clearer now!  Would it be possible for you to also make the code for pre-clustering available if it is not already?  

Thanks again,
Melanie

**Comment by dbeyter** [comment]
Hi Melanie, 

Happy to hear! Of course, I can also make it available here -- though I will need some time for it. I will update you here.

Thanks,
Doruk

**Comment by mkirsche** [comment]
Hi Doruk,

That sounds great - thank you!!

Melanie

**Comment by mkirsche** [comment]
Hi Doruk,

I just wanted to follow up and see if you had an estimated time for when the pre-processing scripts would be available.

Thanks!
Melanie

**Comment by dbeyter** [comment]
Hi Melanie, 

Sorry for the delay -- I should make the pre-clustering available hopefully next week. 

Thanks for the follow up!
Doruk

**Comment by dbeyter** [comment]
Hi Melanie, 

I updated the repo and added the pre-clustering. I also added a step where we find overlaps of SVs and tandem repeat regions, as we merged SVs within and outside SVs differently, using different parameters. I explained it in the readme file. Please note that I use a slightly different input file in this version. 

This is basically the approach we used in our study, mentioned above. 

Please let me know if all works fine on your side, and if you have questions, e.g. how to use it without tandem repeats in consideration, or otherwise. 

Thanks!
Doruk

**Comment by JamesSCLiu** [comment]
Hi Doruk,

I am also using the scripts precluster_svs.py to perform the pre-clustering step. When I execute the script I got an IndexError: 

`Traceback (most recent call last):
  File "<path-to-precluster_svs.py>", line 317, in <module>
    main()
  File "<path-to-precluster_svs.py>", line 313, in main
    combine_sv_info_with_trf_intersections(sv_trr_intersections_fn, out_fn, overlap_percentage, use_trf_coordinates)
  File "<path-to-precluster_svs.py>", line 84, in combine_sv_info_with_trf_intersections
    done_sv_clusters_list = separate_clusters(all_vars, overlap_p)
  File "<path-to-precluster_svs.py>", line 156, in separate_clusters
    todo_by_SVLEN(done_sv_clusters_list, list_of_clusters, overlap_p)
  File "<path-to-precluster_svs.py>", line 239, in todo_by_SVLEN
    prev_SV = G[0][0]
IndexError: list index out of range`

It appears that I got the error when todo_by_SVLEN reaches the first element of all_vars, defined in `all_vars = [ [ [], 0, 0] ]`. I can bypass the error by try except IndexError but not sure if this is appropriate.

Besides, a minor comment for line 104 is that I will get `TypeError: unsupported operand type(s) for +: 'map' and 'list'` in the lambda function.

Thank you!

James

**Comment by dbeyter** [comment]
Hi @JamesSCLiu , 

Do you get this error using the test data or your own dataset? If it is the latter, I would be happy if you can share at least a subset of the data that is generating the same error such that I debug it. 

Thank you for letting me know!
Doruk

**Comment by JamesSCLiu** [comment]
Hi Doruk,

It turns out the definitions of the END sites of my dataset is slightly different from yours, which should be the reason why I got the above error. I modified the input data and executed precluster_svs.py on files of a few chromosomes and received no error so far. I will continue to run the script on all samples. Thank you!

James

**Comment by dbeyter** [comment]
Hi James, 

Good to hear -- thanks for letting know. The END sites are basically BEGIN + SV length in both insertion and deletion events. Although I had not used it for other events, I am guessing that it should work as expected for other SVs such as inversions or duplications -- basically any event that we can explain with 2 breakpoints on the same chromosome.

Best,
Doruk

**Comment by JamesSCLiu** [comment]
Hi Doruk,

Finally, I have completed the pre-clustering step. While for the Merging SVs step, `python main.py FIND_CLIQUES` doesn't work as expected. Seems `main.py` only take 3 arguments:  `part_cluster_fn`, `event`, and `overlap_percentage`?

_P.S. I executed each python script individually for previous steps._

Thank you!

James

**Comment by dbeyter** [comment]
Hi James, 

My apologies for the trouble -- it seems I had a problem while updating the scripts that went unnoticed. Can you check it again, with the toy example provided in the README? 

Thank you,
Doruk

**Comment by dbeyter** [comment]
Hi @mkirsche 

Just FYI, it appears I had a problem that went unnoticed following the addition of the pre-clustering. It should be fixed now, but please let me know if you still experience any problem.

**Comment by JamesSCLiu** [comment]
Hi Doruk,

Thank you for your updates. I can run the code with the toy example and the data of my own. Just need extra time to process chromosomes with several hundred thousands SVs...

James

**Comment by dbeyter** [comment]
Hi James, 

SVs that have different pre-cluster IDs are guaranteed not to be merged into the same SV, so you could have your clique finding runs with smaller input data, with the condition that all SVs that belong to a pre-cluster ID is included in a single run.
